fixtures:
  repositories:
    stdlib:
      repo: "puppetlabs/stdlib"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat"
      ref: "2.2.1"
  symlinks:
    ssh: "#{source_dir}"
